name: Pipeline CI/CD

on:
  push:
    branches:
      - main


jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm i
      - name: Lint
        run: npm run eslint





